server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance?useSSLeUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

